### ISSUE TITLE
File could not be opened successfully

### ISSUE THREAD

**Issue by umutbalkan** [Cobertos/unitypackage_extractor#27]
When I try to unpack unitypackage files I get the following:

any help?

```
> C:\Users\umutb\Downloads\unitypackage_extractor-x64>python -m unitypackage_extractor sounds.unitypackage
> Traceback (most recent call last):
>   File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Python310\lib\site-packages\unitypackage_extractor\__main__.py", line 5, in <module>
>     cli(sys.argv[1:])
>   File "C:\Python310\lib\site-packages\unitypackage_extractor\extractor.py", line 58, in cli
>     extractPackage(args[0], args[1] if len(args) > 1 else "")
>   File "C:\Python310\lib\site-packages\unitypackage_extractor\extractor.py", line 21, in extractPackage
>     with tarsafe.open(name=packagePath, encoding=encoding) as upkg:
>   File "C:\Python310\lib\site-packages\tarsafe\tarsafe.py", line 15, in open
>     return super().open(name, mode, fileobj, bufsize, **kwargs)
>   File "C:\Python310\lib\tarfile.py", line 1620, in open
>     raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
> tarfile.ReadError: file could not be opened successfully:
> - method gz: ReadError('not a gzip file')
> - method bz2: ReadError('not a bzip2 file')
> - method xz: ReadError('not an lzma file')
> - method tar: ReadError('invalid header')
```

**Comment by umutbalkan** [comment]
packages were corrupted somehow
